### ISSUE TITLE
Failed to read/parse Vricon DTM GeoTiFF

### ISSUE THREAD

**Issue by rdkgit** [ngageoint/tiff-java#56]
Please fill out as much known and relevant information as possible.

#### Version Information:

  * TIFF Java Version: 3.00
  * TIFF Java Source: (e.g. Central Repository, Release, Source Code Build) Source code build
  * IDE Name & Version: Emacs
  * Maven Version: (mvn -version) 3.8.5
  * Java Version: (java -version) 19.0.1
  * Platform & OS: linux x86-64
  * Other Relevant Libraries:

#### Expected Results:

Should be able to parse the tiff file and return.

#### Observed Results:

Vricon DTM GeoTiff file; when first parsing, TiffReader spits out exception 

tiff exception is mil.nga.tiff.util.TiffException: Invalid byte order: UH
mil.nga.tiff.util.TiffException: Invalid byte order: UH
	at mil.nga.tiff.TiffReader.readTiff(TiffReader.java:153)
	at mil.nga.tiff.TiffReader.readTiff(TiffReader.java:109)
	at mil.nga.tiff.TiffReader.readTiff(TiffReader.java:52)
	at mil.nga.tiff.TiffReader.readTiff(TiffReader.java:35)

  * What happened instead?  Exception.
  
  * How often does this occur?  Every time.

#### Output:

tiff exception is mil.nga.tiff.util.TiffException: Invalid byte order: UH

 Whats weird is the first bytes of the .tif file are:

0x49 0x49 0x00 0x2a which seem correct for tiff.  II for byte order and 0x00 0x2a for 42 for version.  I don't know where 'UH' is coming from.  Unfortunately, I cannot provide this tif file as its a licenseable tiff provided by MAXAR.

#### Test Files:

I do not have permission to provide this file.  I will see if I can find a similar file that generates same error.

#### Additional Information:

None yet.

**Comment by rdkgit** [comment]
OK, more debugging.  The library is correctly reading II for the byte order.  But its bombing parsing the file elsewhere.  I'll debug more and update this issue.  Sorry for the confusion.

**Comment by rdkgit** [comment]
Here is what is happening when the maxar tif file is attempted to be read.
tiff exception is java.lang.IllegalArgumentException: ERROR: GeoTIFF file is corrupted, this DEM is unusable!
java.lang.IllegalArgumentException: ERROR: GeoTIFF file is corrupted, this DEM is unusable!

**Comment by rdkgit** [comment]
Closing this issue.  Its not a bug with NGA tiff library.  Sorry about that.

**Comment by rdkgit** [comment]
Please feel free to delete this issue to save me from more embarrassment!
